# Generated by Django 4.2.16 on 2025-12-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='order_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='promotions',
            field=models.BooleanField(default=False),
        ),
    ]
