# Generated by Django 4.2.16 on 2025-12-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=10),
        ),
    ]
