# Generated by Django 4.2.16 on 2025-12-27 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_wishlist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='products.order')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('icon', models.CharField(default='bi-check', max_length=50)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='products.ordertracking')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
